name: "CI"
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - name: Run Flake Checks
        run: nix -vL flake check --print-build-logs
