name: "CI"
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: ["simple", "simple-71", "simple-72", "simple-73", "override"]
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - run: cd examples/${{ matrix.example }} && nix develop --command "ls"
